const graphicsCard = [
  {
    manufacturer: 'Zotac ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4090',
    info: 'GDDR6X-24GB, PCIe 4.0',
    price: 164500,
    image: 'images/products/gpu/Zotac-RTX-4090.jpg',
  },
  {
    manufacturer: 'Zotac ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4080',
    info: 'GDDR6X-16GB, PCIe 4.0',
    price: 111500,
    image: 'images/products/gpu/Zotac-RTX-4080.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4070 Ti',
    info: 'GDDR6X-12GB, PCIe 4.0',
    price: 75000,
    image: 'images/products/gpu/Gigabyte-RTX-4070Ti.jpg',
  },
  {
    manufacturer: 'Asus ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4060 Ti',
    info: 'GDDR6-8GB, PCIe 4.0',
    price: 41500,
    image: 'images/products/gpu/Asus-RTX-4060Ti.jpg',
  },
  {
    manufacturer: 'MSI ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3090 Ti',
    info: 'GDDR6X-24GB, PCIe 4.0',
    price: 153000,
    image: 'images/products/gpu/MSI-RTX-3090Ti.jpg',
  },
  {
    manufacturer: 'Zotac ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3080 Ti',
    info: 'GDDR6X-12GB, PCIe 4.0',
    price: 87000,
    image: 'images/products/gpu/Zotac-RTX-3080Ti.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3070 Ti',
    info: 'GDDR6X-8GB, PCIe 4.0',
    price: 57500,
    image: 'images/products/gpu/Gigabyte-RTX-3070Ti.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3060 Ti',
    info: 'GDDR6-8GB, PCIe 4.0',
    price: 40200,
    image: 'images/products/gpu/Gigabyte-RTX-3060Ti.jpg',
  },
  {
    manufacturer: 'Zotac ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3050',
    info: 'GDDR6-8GB, PCIe 4.0',
    price: 25000,
    image: 'images/products/gpu/Zotac-RTX-3050.jpg',
  },
  {
    manufacturer: 'MSI ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Gaming Trio Clasic Radeon RX 7900 XTX',
    info: 'GDDR6-24GB, PCIe 4.0 ',
    price: 108000,
    image: 'images/products/gpu/MSI-RX-7900-XTX.jpg',
  },
  {
    manufacturer: 'MSI ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Gaming Trio Clasic Radeon RX 7900 XT',
    info: 'GDDR6-20GB, PCIe 4.0 ',
    price: 97000,
    image: 'images/products/gpu/MSI-RX-7900-XT.jpg',
  },
  {
    manufacturer: 'Sapphire ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Pulse Radeon RX 7600',
    info: 'GDDR6-8GB, PCIe 4.0 ',
    price: 27400,
    image: 'images/products/gpu/Sapphire-RX-7600.jpg',
  },
  {
    manufacturer: 'Sapphire ',
    brand: 'AMD ',
    series: '6000 ',
    name: 'Nitro Radeon RX 6950 XT',
    info: 'GDDR6-16GB, PCIe 4.0 ',
    price: 67000,
    image: 'images/products/gpu/Sapphire-RX-6950-XT.jpg',
  },
  {
    manufacturer: 'MSI ',
    brand: 'AMD ',
    series: '6000 ',
    name: 'Gaming X Trio Radeon RX 6800 XT',
    info: 'GDDR6-16GB, PCIe 4.0 ',
    price: 65500,
    image: 'images/products/gpu/MSI-RX-6800-XT.jpg',
  },
  {
    manufacturer: 'Asus ',
    brand: 'AMD ',
    series: '6000 ',
    name: 'Dual Radeon RX 6750 XT',
    info: 'GDDR6-12GB, PCIe 4.0 ',
    price: 34300,
    image: 'images/products/gpu/Asus-RX-6750-XT.jpg',
  },
  {
    manufacturer: 'Asus ',
    brand: 'AMD ',
    series: '6000 ',
    name: 'Dual Radeon RX 6650 XT',
    info: 'GDDR6-8GB, PCIe 4.0 ',
    price: 26000,
    image: 'images/products/gpu/Asus-RX-6650-XT.jpg',
  },
];