const graphicsCard = [
  {
    manufacturer: 'Zotac ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4090',
    info: 'GDDR6X-24GB, PCIe 4.0',
    price: 164500,
    image: 'images/products/gpu/Zotac-RTX-4090.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4080 Super Gaming OC',
    info: 'GDDR6X-16GB, PCIe 4.0',
    price: 106600,
    image: 'images/products/gpu/Gigabyte-RTX-4080-Super.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4070 Ti Super Windforce OC',
    info: 'GDDR6X-16GB, PCIe 4.0',
    price: 82000,
    image: 'images/products/gpu/Gigabyte-RTX-4070Ti-Super.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4070 Super Windforce OC',
    info: 'GDDR6X-12GB, PCIe 4.0',
    price: 61900,
    image: 'images/products/gpu/Gigabyte-RTX-4070-Super.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4070 Windforce OC',
    info: 'GDDR6-12GB, PCIe 4.0',
    price: 56000,
    image: 'images/products/gpu/Gigabyte-RTX-4070.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4060 Ti Windforce OC',
    info: 'GDDR6-8GB, PCIe 4.0',
    price: 39400,
    image: 'images/products/gpu/Gigabyte-RTX-4060Ti.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 4000 ',
    name: 'GeForce RTX 4060 Windforce OC',
    info: 'GDDR6-8GB, PCIe 4.0',
    price: 28500,
    image: 'images/products/gpu/Gigabyte-RTX-4060.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3090 Gaming OC',
    info: 'GDDR6X-24GB, PCIe 4.0',
    price: 113000,
    image: 'images/products/gpu/Gigabyte-RTX-3090.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3080 Gaming OC',
    info: 'GDDR6X-10GB, PCIe 4.0',
    price: 78000,
    image: 'images/products/gpu/Gigabyte-RTX-3080.jpg',
  },
  {
    manufacturer: 'Colorful ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3070 Battle AX',
    info: 'GDDR6X-8GB, PCIe 4.0',
    price: 49500,
    image: 'images/products/gpu/Colorful-RTX-3070.jpg',
  },
  {
    manufacturer: 'Gigabyte ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3060 Windforce OC',
    info: 'GDDR6-12GB, PCIe 4.0',
    price: 26200,
    image: 'images/products/gpu/Gigabyte-RTX-3060.jpg',
  },
  {
    manufacturer: 'Zotac ',
    brand: 'nvidia ',
    series: 'RTX 3000 ',
    name: 'GeForce RTX 3050',
    info: 'GDDR6-8GB, PCIe 4.0',
    price: 19600,
    image: 'images/products/gpu/Zotac-RTX-3050.jpg',
  },
  {
    manufacturer: 'ASRock ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Taichi White OC RX 7900 XTX',
    info: 'GDDR6-24GB, PCIe 4.0 ',
    price: 98300,
    image: 'images/products/gpu/ASRock-RX-7900-XTX.jpg',
  },
  {
    manufacturer: 'Sapphire ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Pulse RX 7900 XT',
    info: 'GDDR6-20GB, PCIe 4.0 ',
    price: 73000,
    image: 'images/products/gpu/Sapphire-Pulse-RX-7900-XT.jpg',
  },
  {
    manufacturer: 'Sapphire ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Pulse Radeon RX 7800 XT',
    info: 'GDDR6-16GB, PCIe 4.0 ',
    price: 48000,
    image: 'images/products/gpu/Sapphire-RX-7800-XT.jpg'
  },
  {
    manufacturer: 'Sapphire ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Pulse Radeon RX 7700 XT',
    info: 'GDDR6-12GB, PCIe 4.0 ',
    price: 46000,
    image: 'images/products/gpu/Sapphire-RX-7700-XT.jpg'
  },
  {
    manufacturer: 'Sapphire ',
    brand: 'AMD ',
    series: '7000 ',
    name: 'Pulse Radeon RX 7600',
    info: 'GDDR6-8GB, PCIe 4.0 ',
    price: 23000,
    image: 'images/products/gpu/Sapphire-RX-7600.jpg',
  },  
];