const memory = [
  {
    name: 'Kingston Fury Beast ',
    space: '64GB ',
    type: 'DDR5 6000MHz CL30',
    info: '2 x 32GB',
    price: 16900,
    image: 'images/products/ram/Kingston-Fury-Beast.jpg',
  },
  {
    name: 'Kingston Fury Beast ',
    space: '32GB ',
    type: 'DDR5 6000MHz CL30',
    info: '2 x 16GB',
    price: 8700,
    image: 'images/products/ram/Kingston-Fury-Beast.jpg',
  },
  {
    name: 'Patriot Memory Viper Venom ',
    space: '16GB ',
    type: 'DDR5 5200MHz',
    info: '2 x 8GB',
    price: 7100,
    image: 'images/products/ram/Patriot-Memory-Viper-Venom-16GB-DDR5.jpg',
  },
  {
    name: 'Corsair Vengeance LPX ',
    space: '64GB ',
    type: 'DDR4 3200MHz CL16',
    info: '2 x 32GB',
    price: 11700,
    image: 'images/products/ram/corsair-Vengeance-64GB-DDR4.jpg',
  },
  {
    name: 'TeamGroup T-Force Delta RGB ',
    space: '32GB ',
    type: 'DDR4 3200MHz CL16',
    info: '2 x 16GB',
    price: 6450,
    image: 'images/products/ram/Teamgroup-T-Force-Delta-RGB.jpg',
  },
  {
    name: 'Teamgroup T-Force Delta RGB ',
    space: '16GB ',
    type: 'DDR4 3200MHz CL16',
    info: '2 x 8GB',
    price: 3650,
    image: 'images/products/ram/Teamgroup-T-Force-Delta-RGB.jpg',
  },
];