const powerSupply = [
  {
    manufacturer: 'Thermaltake ',
    name: 'Toughpower GF3 ',
    wattage: '1350W ',
    efficiency: '80+ Gold ',
    modular: 'Fully Modular',
    price: 20700,
    image: 'images/products/psu/Thermaltake-Toughpower-GF3-1350W.jpg',
  },
  {
    manufacturer: 'Thermaltake ',
    name: 'Toughpower GF3 ',
    wattage: '1000W ',
    efficiency: '80+ Gold ',
    modular: 'Fully Modular',
    price: 14800,
    image: 'images/products/psu/Thermaltake-Toughpower-GF3-1000W.jpg',
  },
  {
    manufacturer: 'Thermaltake ',
    name: 'Toughpower GF3 ',
    wattage: '850W ',
    efficiency: '80+ Gold ',
    modular: 'Fully Modular',
    price: 9500,
    image: 'images/products/psu/Thermaltake-Toughpower-GF3-850W.jpg',
  },
  {
    manufacturer: 'Super Flower ',
    name: 'Leadex Platinum ',
    wattage: '1600W ',
    efficiency: '80+ Platinum ',
    modular: 'Fully Modular',
    price: 31500,
    image: 'images/products/psu/Super-Flower-Leadex-Platinum-1600W.jpg',
  },
  {
    manufacturer: 'Super Flower ',
    name: 'Leadex Platinum SE ',
    wattage: '1200W ',
    efficiency: '80+ Platinum ',
    modular: 'Fully Modular',
    price: 17200,
    image: 'images/products/psu/Super-Flower-Leadex-Platinum-SE.jpg',
  },
  {
    manufacturer: 'Super Flower ',
    name: 'Leadex Platinum SE ',
    wattage: '1000W ',
    efficiency: '80+ Platinum ',
    modular: 'Fully Modular',
    price: 15500,
    image: 'images/products/psu/Super-Flower-Leadex-Platinum-SE.jpg',
  },
  {
    manufacturer: 'Super Flower ',
    name: 'Leadex Platinum SE ',
    wattage: '850W ',
    efficiency: '80+ Platinum ',
    modular: 'Fully Modular',
    price: 9200,
    image: 'images/products/psu/Super-Flower-Leadex-Platinum-SE-850W.jpg',
  },
  {
    manufacturer: 'Corsair ',
    name: 'RM1000e ',
    wattage: '1000W ',
    efficiency: '80+ Gold ',
    modular: 'Fully Modular',
    price: 15300,
    image: 'images/products/psu/Corsair-RM1000e.jpg',
  },
  {
    manufacturer: 'Corsair ',
    name: 'RM850e ',
    wattage: '850W ',
    efficiency: '80+ Gold ',
    modular: 'Fully Modular',
    price: 10600,
    image: 'images/products/psu/Corsair-RM850e.jpg',
  },
  {
    manufacturer: 'Corsair ',
    name: 'RM750e ',
    wattage: '750W ',
    efficiency: '80+ Gold ',
    modular: 'Fully Modular',
    price: 10300,
    image: 'images/products/psu/Corsair-RM750e.jpg',
  },
];